### ISSUE TITLE
Rename compiled output file

### ISSUE THREAD

**Issue by shikulja** [allfoxwy/vanilla-dll-sideloader#2]
`sideload-DLL.dll` to `sideload.dll` And it’s clear that this is a library

**Comment by allfoxwy** [comment]
There are more things than DLL that could be sideload, guess I would keep it this way. For now.

**Comment by allfoxwy** [comment]
Closing for now.

**Comment by shikulja** [comment]
I would like to leave this problem open, it is not very important. But in the future something could be done about this

**Comment by allfoxwy** [comment]
Sure
